parameters:
    locale: 'en'
    manuscript_directory: '%kernel.project_dir%/public/uploads/manuscript'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    App\CommandHandler\CreateUserCommandHandler:
        tags: ['messenger.message_handler']

    App\CommandHandler\UploadManuscriptCommandHandler:
      tags: ['messenger.message_handler']

    App\CommandHandler\AddBookCommandHandler:
        tags: ['messenger.message_handler']

    App\CommandHandler\ReviewBookCommandHandler:
        tags: ['messenger.message_handler']

    App\CommandHandler\AssignEditorCommandHandler:
        tags: ['messenger.message_handler']

    App\CommandHandler\AddNoteCommandHandler:
        tags: ['messenger.message_handler']

    App\CommandHandler\ProcessBookCommandHandler:
        tags: ['messenger.message_handler']

    App\CommandHandler\SearchBookCommandHandler:
        tags: ['messenger.message_handler']

    App\Helper\Orm:
        arguments: ['@doctrine.orm.entity_manager']